name: Sync Upstream Repo

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0  # Fetches all branches

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Authenticate and Fetch Updates
        run: |
          git remote add upstream https://x-access-token:${{ secrets.KEQ_TOKEN }}@github.com/kimitasharrif/services-booking-site.git || echo "Upstream already exists"
          git fetch upstream --prune  # Fetch all branches

      - name: Sync All Branches
        run: |
          for branch in $(git branch -r | grep upstream/ | sed 's/upstream\///'); do
            git checkout -B $branch upstream/$branch || echo "Branch $branch does not exist upstream"
            git merge upstream/$branch --allow-unrelated-histories || echo "No new updates in $branch"
            git push origin $branch || echo "Failed to push $branch"
          done

